interface Object {
  [itemName: string]: string;
}

let Persian: Object = {
  // Main
  title: 'پیش بینی حرفه ای مسابقات فوتبال',
  homepage: 'صفحه اصلی',
  jobs: 'مشاغل',
  hallOfFame: 'تالار افتخارات',
  notFound: 'موردی یافت نشد!',
  logout: 'خروج',
  changeInformation: 'ویرایش اطلاعات',
  changePassword: 'تغییر کلمه عبور',
  transactions: 'تراکنش ها',
  dash: '-',
  questionMark: '?',
  threeDots: '...',
  buy: 'خرید',
  toman: 'تومان',
  submit: 'ثبت',
  paid: 'پرداخت شده',
  notPaid: 'پرداخت نشده',
  payNow: 'پرداخت',
  submitPay: 'ثبت پرداخت',
  totalAmount: 'مبلغ کل',
  componentAmount: 'هزینه مسابقه',
  serviceAmount: 'هزینه خدمات',
  edit: 'ویرایش',
  delete: 'حذف',
  no: 'خیر',
  yes: 'بلی',

  // Auth
  login: 'ورود',
  register: 'ثبت نام',
  forgetPassword: 'فراموشی کلمه عبور',
  email: 'پست الکترونیک',
  password: 'کلمه عبور',
  mobile: 'شماره همراه',
  name: 'نام',
  firstName: 'نام',
  lastName: 'نام خانوادگی',
  currentPassword: 'کلمه عبور فعلی',
  newPassword: 'کلمه عبور جدید',
  confirmNewPassword: 'تکرار کلمه عبور جدید',
  titleText: 'عنوان',
  description: 'توضیحات',
  phone: 'شماره تماس',
  link: 'وب سایت',
  status: 'وضعیت',
  uploadAvatar: 'آپلود تصویر',
  number: 'عدد',
  deleteQuestion: 'آیا از حذف این مورد اطمینان دارید؟',
  activeQuestion: 'آیا از فعال کردن این مورد اطمینان دارید؟',
  price: 'قیمت',
  url: 'آدرس',

  // Home
  activeCompetitions: 'مسابقات فعال',
  myCompetitions: 'مسابقات من',
  archivedCompetitions: 'مسابقات گذشته',

  // Competitions
  matches: 'بازی ها',
  table: 'جدول',
  stats: 'آمار',
  champion: 'قهرمان',
  varzesh3: 'ورزش 3',
  predict: 'پیشبینی',
  choosePeriodOfCompetition: 'انتخاب هفته مسابقات',
  matchScore: 'نتیجه بازی',
  delayed: 'معوقه',
  point: 'امتیاز',
  otherPeoplePredictions: 'پیشبینی سایر شرکت کنندگان',
  bestThree: '3 شرکت کننده برتر',
  otherUsers: 'سایر شرکت کنندگان',
  periods: 'هفته ها',
  myPredict: 'پیشبینی من',
  winner: 'قهرمان',
  details: 'جزییات',
  finishedCompetition: 'تمام شده',
  tableDetails: 'جزییات امتیاز',
  exactPredict: 'پیشبینی دقیق',
  differencePredict: 'پیشبینی تفاضل',
  winnerPredict: 'پیشبینی برنده',
  wrongPredict: 'پیشبینی اشتباه',
  emptyPredict: 'پیشبینی نشده',
  championPredict: 'پیشبینی قهرمانی',
  currect: 'درست',
  finishCompetition: 'اتمام مسابقه',

  // Guest

  // Admin
  manageUsers: 'مدیریت کاربران',
  manageCompetitions: 'مدیریت مسابقات',
  manageTeams: 'مدیریت تیم ها',
  managePeriods: 'مدیریت هفته ها',
  manageMatches: 'مدیریت بازی ها',
  addTeam: 'اضافه کردن تیم',
  addCompetition: 'اضافه کردن مسابقه',
  addPeriod: 'اضافه کردن هفته',
  addMatch: 'اضافه کردن بازی',
  championPredictionDateTime: 'مهلت انتخاب تیم قهرمان',
  setActive: 'هفته فعال',
  submitScore: 'ثبت نتیجه',
  submitTime: 'ثبت زمان',

  // Toasts Messages
  technicalProblem: 'مشکل فنی',
  emailInvalid: 'پست الکترونیک وارد شده نامعتبر می باشد!',
  passwordInvalid: 'کلمه عبور وارد شده نامعتبر می باشد!',
  firstNameInvalid: 'نام وارد شده نامعتبر می باشد!',
  lastNameInvalid: 'نام خانوادگی وارد شده نامعتبر می باشد!',
  mobileInvalid: 'شماره همراه وارد شده نامعتبر می باشد!',
  pleaseEnterYourPredictCurrectly: 'نتیجه خود را به طور صحیح وارد نمایید!',
  currentPasswordInvalid: 'کلمه عبور فعلی وارد شده نامعتبر می باشد!',
  newPasswordInvalid: 'کلمه عبور جدید وارد شده نامعتبر می باشد!',
  confirmNewPasswordInvalid: 'تکرار کلمه عبور جدید وارد شده نامعتبر می باشد!',
  newPasswordsNotMatch: 'کلمه عبور جدید و تکرار کلمه عبور جدید مطابقت ندارد!',
  titleInvalid: 'عنوان وارد شده نامعتبر می باشد!',
  descriptionInvalid: 'توضیحات وارد شده نامعتبر می باشد!',
  linkInvalid: 'وب سایت وارد شده نامعتبر می باشد!',
  dateTimeInvalid: 'زمان انتخاب شده معتبر نمی باشد!',
  urlInvalid: 'آدرس وارد شده معتبر نمی باشد!',
  mustSelectTeam: 'تیمی برای این مسابقه انتخاب نشده',
  teamInvalid: 'تیم انتخاب شده معتبر نمی باشد!',
};

export default Persian;
